language: node_js
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false
node_js:
  - '8'
script:
  - yarn add next react react-dom
  - yarn prettier-check
  - yarn lint
  - yarn build
  - yarn test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
